apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
     app: petclinic
     type: front-end
spec:
  template:
     metadata:
       name: petclinic-pod
       labels: 
         app: petclinic
         type: front-end
     spec:
         containers:
           - name: petclinic-erp
             image: "tquatrep/petclinic:1.0.0"
             ports:
             - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      type: front-end
